name: Integration Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Build and start containers
        run: docker-compose up -d --build
        
      - name: Wait for app to be ready
        run: sleep 10
        
      - name: Test app response
        run: |
          curl -f http://localhost || exit 1
          
      - name: Shut down containers
        run: docker-compose down

